apiVersion: v1
kind: Service
metadata:
  name: j-10000
  namespace: ops-backend
spec:
  type: NodePort
  selector:
    app: j-10000
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32073
      name: runserver
